In [1]:
import pandas as pd
import numpy as np

|메뉴|가격|판매량|
|---|---|---|
|아메리카노|4500|152|
|카페라떼|5000|98|
|바닐라라떼|5500|67|
|카푸치노|5000|45|

In [ ]:
data= {
    '메뉴': ['아메리카노', '카페라떼', '바닐라라떼', '카푸치노'],
    '가격': [4500, 5000, 5500, 5000],
    '판매량': [152, 98, 67, 45]
}
data

df = pd.DataFrame(data) #딕셔너리로 만듦
df

# 엔티티(entity), 개체 객체 테이블 표

      메뉴    가격  판매량
0  아메리카노  4500  152
1   카페라떼  5000   98
2  바닐라라떼  5500   67
3   카푸치노  5000   45

In [ ]:
type(df)

pandas.DataFrame

In [ ]:
s = pd.Series([1,2,3,4])
df = pd.DataFrame({'value': [1,2,3,4]})

print(s.ndim)#시리즈 - 1차원 데이터프레임 - 2차원
print(df.ndim)

1
2

In [ ]:
data= {
    '메뉴': ['아메리카노', '아메리카노', '아메리카노', '아메리카노'], #식별자를 보고 판단
    '가격': [4500, 5000, 5500, 5000],
    '판매량': [152, 152, 67, 45]
}

df = pd.DataFrame(data)
df # 앞에 있는 0, 1 등을 보고 다름을 알 수 있음 이를 식별자라 함
#첫번째 행과 두번째 행은 같은 속성을 공유하고 있다

      메뉴    가격  판매량
0  아메리카노  4500  152
1  아메리카노  5000  152
2  아메리카노  5500   67
3  아메리카노  5000   45

In [ ]:
data = {
    'tracking_no': ['T1ooo1', 'T10002', 'T10003'],
    'destination': ['서울', '부산', '대전'],
    'weight_kg': [2.4, 5.1, 1.8],
    'delivered': [True, False, True]
}
delivers = pd.DataFrame(data)
delivers #여러개의 열이 붙어있음
#행이든 열이든 어떤 걸 가져와도 시리즈임

  tracking_no destination  weight_kg  delivered
0      T1ooo1          서울        2.4       True
1      T10002          부산        5.1      False
2      T10003          대전        1.8       True

In [ ]:
delivers.loc[0] #행 단위로 하는 건 따로 따로 빼줘야 가능

tracking_no    T1ooo1
destination        서울
weight_kg         2.4
delivered        True
Name: 0, dtype: object

In [9]:
type(delivers.loc[0])

pandas.Series

In [ ]:
#delivers.loc['delivered'] 
delivers['delivered']

0     True
1    False
2     True
Name: delivered, dtype: bool

In [ ]:
delivers.shape #4개의 속성을 공유하고 있음

(3, 4)

In [14]:
row_count = delivers.shape[0]
print(f'행의 갯수 = {row_count}')

column_count = delivers.shape[1]
print(f'열의 갯수 = {column_count}')

행의 갯수 = 3
열의 갯수 = 4

In [ ]:
data = {
    'product': ['노트북', '모니터', '키보드'],
    'quantity': [1,2,3],
    'unit_price': [1350000, 280000, 35000]
}

products = pd.DataFrame(data)
products # 데이터가

  product  quantity  unit_price
0     노트북         1     1350000
1     모니터         2      280000
2     키보드         3       35000

In [ ]:
print(products.index)
print(products.columns) 

#컬럼으로 시리즈의 인덱스
#각각의 행을 인덱스로 구분?

RangeIndex(start=0, stop=3, step=1)
Index(['product', 'quantity', 'unit_price'], dtype='str')

In [19]:
data = {
    'product': ['노트북', '모니터', '키보드'],
    'quantity': [1,2,3],
    'unit_price': [1350000, 280000, 35000]
}

products = pd.DataFrame(data, index=['P001', 'P002','P003'])
products

     product  quantity  unit_price
P001     노트북         1     1350000
P002     모니터         2      280000
P003     키보드         3       35000

In [ ]:
product = pd.Series(['노트북', '모니터', '키보드'])
quantity = pd.Series([1,2,3])
unit_price = pd.Series([1350000, 280000, 35000])

df = pd.DataFrame([product, quantity, unit_price])
df # 행 취급하고 있음

         0       1      2
0      노트북     모니터    키보드
1        1       2      3
2  1350000  280000  35000

In [21]:
data = {
    'product': product,
    'quantity': quantity,
    'unit_price': unit_price
}
pd.DataFrame(data)

  product  quantity  unit_price
0     노트북         1     1350000
1     모니터         2      280000
2     키보드         3       35000

In [28]:
data = {
    'product': product,
    'quantity': quantity,
    'unit_price': unit_price
}
df = pd.DataFrame(data)
df['product'] #열 선택

0    노트북
1    모니터
2    키보드
Name: product, dtype: str

In [29]:
product_column= df['product']
product_column

0    노트북
1    모니터
2    키보드
Name: product, dtype: str

In [30]:
print(product_column.name)
print(product_column.dtype)
print(product_column.shape)
print(product_column.ndim)

product
str
(3,)
1

In [31]:
total_price = df['quantity'] * df['unit_price']
print(total_price)

0    1350000
1     560000
2     105000
dtype: int64

In [ ]:
df[['quantity', 'unit_price']] #시리즈의 배열이 아니라 
type(df[['quantity', 'unit_price']]) #데이터 프레임으로 가지고 옴

pandas.DataFrame

In [ ]:
df[['quantity']] #단일 선택시 시리즈로 []빼고 가져오고 2개이상 가져오고 싶음 배열로 데이터프레임
type(df[['quantity']])

pandas.DataFrame

In [ ]:
#모든 행들이 같은 속성을 공유

df.dtypes #개별 속성의 특징을 보여줌

product         str
quantity      int64
unit_price    int64
dtype: object

In [ ]:
df.info()
#
# 인덱스 지정이 아니라 숫자로 되어있음
#열의 갯수
#열에 대한 상세 정보
#null도 일종의 값 
# null 없이 값 다 채워짐
#표의 모양을 알 수 있음, 분석 위한 정보는 아님

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     3 non-null      str
 1   quantity    3 non-null      int64
 2   unit_price  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [37]:
df

  product  quantity  unit_price
0     노트북         1     1350000
1     모니터         2      280000
2     키보드         3       35000

In [ ]:
df.T #행과 열이 바뀜

                  0       1      2
product         노트북     모니터    키보드
quantity          1       2      3
unit_price  1350000  280000  35000

In [39]:
#데이터프레임 탐색
import pandas as pd
import numpy as np

orders = pd.DataFrame(
    {
        "order_date": pd.to_datetime([
            "2026-08-01", "2026-08-01", "2026-08-02", "2026-08-03",
            "2026-08-04", "2026-08-05", "2026-08-05", "2026-08-06",
            "2026-08-07", "2026-08-08", "2026-08-09", "2026-08-10",
        ]),
        "customer": pd.Series(
            ["민준", "서연", "지우", "도윤", "하준", "서연",
             "민준", "지우", "도윤", "하준", "민준", "서연"],
            dtype="string",
        ),
        "region": pd.Series(
            ["서울", "부산", "서울", "대전", "부산", "서울",
             "대전", "서울", "부산", "대전", "서울", "부산"],
            dtype="category",
        ),
        "product": pd.Series(
            ["키보드", "모니터", "마우스", "키보드", "모니터", "키보드",
             "마우스", "모니터", "키보드", "마우스", "모니터", "키보드"],
            dtype="category",
        ),
        "quantity": pd.Series(
            [2, 1, 3, 2, 1, 4, 2, 1, 5, 2, 1, 3],
            dtype="Int64",
        ),
        "unit_price": [
            45000, 320000, 25000, 45000, 320000, 45000,
            25000, 320000, 45000, 25000, 320000, 45000,
        ],
        "discount_rate": [
            0.00, 0.10, np.nan, 0.05, 0.00, 0.10,
            0.00, np.nan, 0.05, 0.00, 0.10, 0.00,
        ],
        "paid": pd.Series(
            [True, True, False, True, True, True,
             False, True, True, pd.NA, True, False],
            dtype="boolean",
        ),
    },
    index=pd.Index(
        [f"O{i:03d}" for i in range(1, 13)],
        name="order_id",
    ),
)

orders["customer"] = pd.array(
    ["민준", "서연", "지우", "도윤", "하준", "서연",
     "민준", "지우", "도윤", "하준", "민준", "서연"],
    dtype="string",
)
orders["region"] = pd.Categorical(
    ["서울", "부산", "서울", "대전", "부산", "서울",
     "대전", "서울", "부산", "대전", "서울", "부산"]
)
orders["product"] = pd.Categorical(
    ["키보드", "모니터", "마우스", "키보드", "모니터", "키보드",
     "마우스", "모니터", "키보드", "마우스", "모니터", "키보드"]
)
orders["quantity"] = pd.array(
    [2, 1, 3, 2, 1, 4, 2, 1, 5, 2, 1, 3],
    dtype="Int64",
)
orders["paid"] = pd.array(
    [True, True, False, True, True, True,
     False, True, True, pd.NA, True, False],
    dtype="boolean",
)

print(orders)

         order_date customer region product  quantity  unit_price  \
order_id
O001     2026-08-01       민준     서울     키보드         2       45000
O002     2026-08-01       서연     부산     모니터         1      320000
O003     2026-08-02       지우     서울     마우스         3       25000
O004     2026-08-03       도윤     대전     키보드         2       45000
O005     2026-08-04       하준     부산     모니터         1      320000
O006     2026-08-05       서연     서울     키보드         4       45000
O007     2026-08-05       민준     대전     마우스         2       25000
O008     2026-08-06       지우     서울     모니터         1      320000
O009     2026-08-07       도윤     부산     키보드         5       45000
O010     2026-08-08       하준     대전     마우스         2       25000
O011     2026-08-09       민준     서울     모니터         1      320000
O012     2026-08-10       서연     부산     키보드         3       45000

          discount_rate   paid
order_id
O001               0.00   True
O002               0.10   True
O003                NaN  False
O004               0.05   True
O005               0.00   True
O006               0.10   True
O007               0.00  False
O008                NaN   True
O009               0.05   True
O010               0.00   <NA>
O011               0.10   True
O012               0.00  False

In [ ]:
orders.head() #딱 다섯개만 보임

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,0.00,True
O002,2026-08-01,서연,부산,모니터,1,320000,0.10,True
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False
O004,2026-08-03,도윤,대전,키보드,2,45000,0.05,True
O005,2026-08-04,하준,부산,모니터,1,320000,0.00,True

In [ ]:
orders.head(1) #하나만 보임

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,0.0,True

In [ ]:
orders.head(-1) # 전체에서 뒤에꺼 빼고 보여줌

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,0.00,True
O002,2026-08-01,서연,부산,모니터,1,320000,0.10,True
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False
O004,2026-08-03,도윤,대전,키보드,2,45000,0.05,True
O005,2026-08-04,하준,부산,모니터,1,320000,0.00,True
O006,2026-08-05,서연,서울,키보드,4,45000,0.10,True
O007,2026-08-05,민준,대전,마우스,2,25000,0.00,False
O008,2026-08-06,지우,서울,모니터,1,320000,NaN,True
O009,2026-08-07,도윤,부산,키보드,5,45000,0.05,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.00,<NA>
O011,2026-08-09,민준,서울,모니터,1,320000,0.10,True

In [43]:
orders.tail()

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O008,2026-08-06,지우,서울,모니터,1,320000,NaN,True
O009,2026-08-07,도윤,부산,키보드,5,45000,0.05,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.00,<NA>
O011,2026-08-09,민준,서울,모니터,1,320000,0.10,True
O012,2026-08-10,서연,부산,키보드,3,45000,0.00,False

In [ ]:
orders.tail(1) #표본 꺼내온 거

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O012,2026-08-10,서연,부산,키보드,3,45000,0.0,False

In [ ]:
#샘플링-임의로 표본 가져오기
orders.sample() #기본적으로 한 개 집어오니까 여러개 보고 싶으면 () 사이에 숫자 넣으면 옴

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O005,2026-08-04,하준,부산,모니터,1,320000,0.0,True

In [ ]:
#씨드-임의로 섞어도 고정을 해주는 ..동일한 게 송출
orders.sample(2, random_state=42) #42는 그냥 임의의 숫자 아무거나 넣어도 됨 값을 고정시키는 게 중요

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O011,2026-08-09,민준,서울,모니터,1,320000,0.1,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.0,<NA>

In [47]:
#비율을 표본 채취하고 싶어
#표본조사 - 일정 비율 데이터만 꺼내오세요
#행의 갯수 지정이 아니라 
orders.sample(frac=0.25) #25퍼센트의 행을 가져와라-데이터프레임으로 가지고 옴

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O012,2026-08-10,서연,부산,키보드,3,45000,0.00,False
O004,2026-08-03,도윤,대전,키보드,2,45000,0.05,True
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False

In [ ]:
#이전까지는 데이터의 모양을 보았고
#이제부터는 데이터의 값을 볼 거야

In [ ]:
df.describe()

#count: 결측치을 제외한 값의 갯수
#평균값
#표준편차
#최솟값
#1/4
#중앙값
#3/4
#최댓값

       quantity    unit_price
count       3.0  3.000000e+00
mean        2.0  5.550000e+05
std         1.0  6.993032e+05
min         1.0  3.500000e+04
25%         1.5  1.575000e+05
50%         2.0  2.800000e+05
75%         2.5  8.150000e+05
max         3.0  1.350000e+06

In [ ]:
orders.describe() #기술통계

                order_date  quantity     unit_price  discount_rate
count                   12      12.0      12.000000      10.000000
mean   2026-08-05 02:00:00      2.25  131666.666667       0.040000
min    2026-08-01 00:00:00       1.0   25000.000000       0.000000
25%    2026-08-02 18:00:00       1.0   40000.000000       0.000000
50%    2026-08-05 00:00:00       2.0   45000.000000       0.025000
75%    2026-08-07 06:00:00       3.0  320000.000000       0.087500
max    2026-08-10 00:00:00       5.0  320000.000000       0.100000
std                    NaN  1.288057  139338.262926       0.045947

In [50]:
orders[
    ['quantity', 'unit_price', 'discount_rate']
].describe()

selected = orders[
    ['quantity', 'unit_price', 'discount_rate']
]
selected.describe()

       quantity     unit_price  discount_rate
count      12.0      12.000000      10.000000
mean       2.25  131666.666667       0.040000
std    1.288057  139338.262926       0.045947
min         1.0   25000.000000       0.000000
25%         1.0   40000.000000       0.000000
50%         2.0   45000.000000       0.025000
75%         3.0  320000.000000       0.087500
max         5.0  320000.000000       0.100000

In [ ]:
orders.nunique() # 범주형 데이터 맵핑된 값 분류할 때 볼 수 있는 데이터

order_date       10
customer          5
region            3
product           3
quantity          5
unit_price        3
discount_rate     3
paid              2
dtype: int64