In [1]:
import pandas as pd
import numpy as np

In [2]:
IRIS_CSV_PATH = '../data/iris.csv'

In [ ]:
pd.read_csv(IRIS_CSV_PATH) #데이터프레임으로 반환해줌
#pd.read_excel()

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [4]:
df = pd.read_csv(IRIS_CSV_PATH)
df.shape

(150, 5)

In [7]:
df = pd.read_csv(
    IRIS_CSV_PATH,
    skiprows=1,
    )
df

     5.1  3.5  1.4  0.2  0
0    4.9  3.0  1.4  0.2  0
1    4.7  3.2  1.3  0.2  0
2    4.6  3.1  1.5  0.2  0
3    5.0  3.6  1.4  0.2  0
4    5.4  3.9  1.7  0.4  0
..   ...  ...  ...  ... ..
144  6.7  3.0  5.2  2.3  2
145  6.3  2.5  5.0  1.9  2
146  6.5  3.0  5.2  2.0  2
147  6.2  3.4  5.4  2.3  2
148  5.9  3.0  5.1  1.8  2

[149 rows x 5 columns]

In [9]:
df = pd.read_csv(
    IRIS_CSV_PATH,
    skiprows=1,
    header=None,
    )
df.head()

     0    1    2    3  4
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0
4  5.0  3.6  1.4  0.2  0

In [13]:
IRIS_COLUMNS = ['sepal_length', 'speal_width', 'petal_length','petal_width', 'species']

df = pd.read_csv(
    IRIS_CSV_PATH,
    skiprows=1,
    header=None,
    names=IRIS_COLUMNS
    )

df

     sepal_length  speal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

## 데이터 탐색의 목적
데이터 탐색 과정(표의 모양 확인)에서 다음과 같은 질문에 대한 대답을 합니다.

데이터는 몇 행 몇 열인가?
어떤 컬럼이 존재하는가?
각 컬럼은 어떤 타입인가?
데이터의 앞부분과 뒷부분은 어떻게 생겼는가?
결측값은 존재하는가?
수치 데이터의 범위는 어느 정도인가?
범주에는 어떤 값들이 존재하는가?
각 범주는 몇 번 등장하는가?

In [14]:
df.tail()

     sepal_length  speal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

In [15]:
df.sample(n=5)

     sepal_length  speal_width  petal_length  petal_width  species
123           6.3          2.7           4.9          1.8        2
78            6.0          2.9           4.5          1.5        1
10            5.4          3.7           1.5          0.2        0
0             5.1          3.5           1.4          0.2        0
37            4.9          3.6           1.4          0.1        0

In [16]:
df.sample(frac=0.1)

     sepal_length  speal_width  petal_length  petal_width  species
8             4.4          2.9           1.4          0.2        0
137           6.4          3.1           5.5          1.8        2
30            4.8          3.1           1.6          0.2        0
102           7.1          3.0           5.9          2.1        2
106           4.9          2.5           4.5          1.7        2
6             4.6          3.4           1.4          0.3        0
72            6.3          2.5           4.9          1.5        1
77            6.7          3.0           5.0          1.7        1
62            6.0          2.2           4.0          1.0        1
56            6.3          3.3           4.7          1.6        1
147           6.5          3.0           5.2          2.0        2
82            5.8          2.7           3.9          1.2        1
20            5.4          3.4           1.7          0.2        0
114           5.8          2.8           5.1          2.4        2
58            6.6          2.9           4.6          1.3        1

In [17]:
df.dtypes

sepal_length    float64
speal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   speal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [20]:
df.isna()

df.isna().sum()

sepal_length    0
speal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.describe() #나머지 수치형// species은 범주형이니 필요없음

       sepal_length  speal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

### 기술통계에서 살펴보는 데이터와 목적
중심경향치(데이터가 어디에 모여 있는가?)
 -평균(mean): 모든 값을 더한 뒤 갯수로 나눈 값
 -중앙값(median): 크기 순서대로 나열했을 때 정 중앙에 있는 값
 -최빈값(mode): 데이터에서 가장 자주 등장하는 값

산포도(데이터가 어떻게 퍼져있는지)
 -분산(variance): 평균에서 데이터가 떨어진 정도를 제곱해서 구한 평균
 -표준편차(standard deviation): 분산의 양의 제곱근
 -사분위수(quartile): 전제 데이터를 4등분한 위치의 값

분포의 형태(데이터의 모양)
 -왜도: 분포가 한쪽으로 치우쳐진 정도
 -첨도: 분포의 뾰족한 정도

In [24]:
df['speal_width'].median()

np.float64(3.0)

In [27]:
# setosa,versicolor,virginica

species_map = {
    0: 'setosa',
    1: 'versicolor',
    2: 'virginica',
}

#파생변수 , 원본에 웬만하면 추가하지 말 것(원본 유지), 

#원본데이터 복사

#(variable) species_df: DataFrame
species_df = df.copy()
species_df

     sepal_length  speal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [31]:
species_map = {
    0: 'setosa',
    1: 'versicolor',
    2: 'virginica',
}

df['species'].map(species_map)


species_df['species_code']=df['species'].map(species_map)
species_df

,sepal_length,speal_width,petal_length,petal_width,species,species_code
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [32]:
species_df.head()

   sepal_length  speal_width  petal_length  petal_width  species species_code
0           5.1          3.5           1.4          0.2        0       setosa
1           4.9          3.0           1.4          0.2        0       setosa
2           4.7          3.2           1.3          0.2        0       setosa
3           4.6          3.1           1.5          0.2        0       setosa
4           5.0          3.6           1.4          0.2        0       setosa

In [34]:
species_df['species'].unique()
species_df['species'].nunique()

3

In [35]:
species_df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [37]:
species_df['species'].value_counts(normalize=True)
species_df['species'].value_counts(normalize=True) * 100 #백분율

species
0    33.333333
1    33.333333
2    33.333333
Name: proportion, dtype: float64

In [40]:
df_ng = df.head().copy()
df_ng['sepal_length']= df_ng['sepal_length'].astype('str')
df_ng.loc[2, 'sepal_length'] = 'unknown'

In [ ]:
df_ng #결측치 만든 거 null 대신 문자열 언노운으로..

  sepal_length  speal_width  petal_length  petal_width  species
0          5.1          3.5           1.4          0.2        0
1          4.9          3.0           1.4          0.2        0
2      unknown          3.2           1.3          0.2        0
3          4.6          3.1           1.5          0.2        0
4          5.0          3.6           1.4          0.2        0

In [ ]:
df_ng.isna() # 실제 결측치가 있음에도 없다고 나오면 어떻게?

   sepal_length  speal_width  petal_length  petal_width  species
0         False        False         False        False    False
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False