## 월별 물동량의 장기 성장/계절성/환적 구조 파악

In [5]:
import pandas as pd
import numpy as np

In [6]:
CSV_PATH = './data/부산항만공사_물동량 예측.csv'

In [8]:
from pathlib import Path

data_dir = Path("./data")

for file in data_dir.glob("*.csv"):
    print(file)

data\부산항만공사_물동량 예측_20250331.csv

In [11]:
CSV_PATH = Path("./data/부산항만공사_물동량 예측_20250331.csv")
df = pd.read_csv(CSV_PATH, encoding='cp949')

In [12]:
df.head()

     연도   월       연월 수출입구분 수출입구분설명        물동량
0  2003   2  2003-02    OT    수출환적  161074.50
1  2003  11  2003-11    IT    수입환적  170733.50
2  2006   1  2006-01    OT    수출환적  203348.25
3  2018   1  2018-01    OO      수출  413797.75
4  2013   6  2013-06    OO      수출  389650.25

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1376 entries, 0 to 1375
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   연도       1376 non-null   int64
 1   월        1376 non-null   int64
 2   연월       1376 non-null   str
 3   수출입구분    1376 non-null   str
 4   수출입구분설명  1376 non-null   str
 5   물동량      1376 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 64.6 KB

In [14]:
print(df.columns.to_list())

['연도', '월', '연월', '수출입구분', '수출입구분설명', '물동량']

In [15]:
df['수출입구분설명'].value_counts()

수출입구분설명
수출      398
수입      398
수출환적    290
수입환적    290
Name: count, dtype: int64

In [ ]:
df_sorted = df.sort_values(by='연월')
df_sorted

        연도  월       연월 수출입구분 수출입구분설명        물동량
602   1992  1  1992-01    OO      수출  104567.00
864   1992  1  1992-01    II      수입   92005.00
735   1992  2  1992-02    OO      수출  103903.00
491   1992  2  1992-02    II      수입   91669.00
641   1992  3  1992-03    II      수입  105276.00
...    ... ..      ...   ...     ...        ...
550   2025  1  2025-01    OO      수출  434429.50
207   2025  2  2025-02    OT    수출환적  599626.75
50    2025  2  2025-02    OO      수출  437906.75
858   2025  2  2025-02    II      수입  392441.25
1156  2025  2  2025-02    IT    수입환적  533568.75

[1376 rows x 6 columns]

In [21]:
df=(df.sort_values(by=["연도","월"],ascending=[True,True]).reset_index(drop=True))
df

        연도  월       연월 수출입구분 수출입구분설명        물동량
0     1992  1  1992-01    OO      수출  104567.00
1     1992  1  1992-01    II      수입   92005.00
2     1992  2  1992-02    II      수입   91669.00
3     1992  2  1992-02    OO      수출  103903.00
4     1992  3  1992-03    OO      수출  137082.00
...    ... ..      ...   ...     ...        ...
1371  2025  1  2025-01    II      수입  468006.50
1372  2025  2  2025-02    OO      수출  437906.75
1373  2025  2  2025-02    OT    수출환적  599626.75
1374  2025  2  2025-02    II      수입  392441.25
1375  2025  2  2025-02    IT    수입환적  533568.75

[1376 rows x 6 columns]

In [ ]:
grouped = df.groupby('연도')
result = grouped['물동량'].mean()
print(result)

#년도마다 물동량이 올라가고 있기에(일부 년도에서 감소한 부분도 있으나) 
#장기적으로 성장하고 있다고 볼 수 있습니다.

연도
1992    109807.250000
1993    122551.458333
1994    149271.541667
1995    170430.572917
1996    181751.458333
1997    200465.062500
1998    221304.645833
1999    235870.083333
2000    265929.906250
2001    168183.369792
2002    196960.166667
2003    216844.635417
2004    239390.937500
2005    246737.390625
2006    250814.760417
2007    276288.328125
2008    280273.541667
2009    249596.041667
2010    295720.744792
2011    337186.536458
2012    355128.692708
2013    368460.385417
2014    389235.067708
2015    405598.427083
2016    405339.401042
2017    426947.401042
2018    451303.666667
2019    458166.671875
2020    454666.562500
2021    473044.369792
2022    459962.385417
2023    482364.750000
2024    508375.416667
2025    511203.531250
Name: 물동량, dtype: float64

In [63]:
resul = result.pct_change() * 100
resul

#년도마다 물동량이 올라가고 있기에(일부 년도에서 감소한 부분도 있으나) 
#장기적으로 성장하고 있다고 볼 수 있습니다.

연도
1992          NaN
1993    11.605981
1994    21.803154
1995    14.174859
1996     6.642520
1997    10.296261
1998    10.395619
1999     6.581623
2000    12.744229
2001   -36.756504
2002    17.110370
2003    10.095680
2004    10.397445
2005     3.068810
2006     1.652514
2007    10.156327
2008     1.442411
2009   -10.945557
2010    18.479741
2011    14.021942
2012     5.321137
2013     3.754046
2014     5.638240
2015     4.203979
2016    -0.063863
2017     5.330841
2018     5.704746
2019     1.520707
2020    -0.763938
2021     4.042041
2022    -2.765488
2023     4.870478
2024     5.392323
2025     0.556304
Name: 물동량, dtype: float64

In [ ]:
resull = pd.DataFrame({
    '연도별 물동량 평균': result,
    '전년 대비 증감률(%)': resul
})

resull['전년 대비 증감률(%)'] = resull['전년 대비 증감률(%)'].round(2)

resull
#년도마다 물동량이 올라가고 있기에(일부 년도에서 감소한 부분도 있으나) 
#장기적으로 성장하고 있다고 볼 수 있습니다.

         연도별 물동량 평균  전년 대비 증감률(%)
연도
1992  109807.250000           NaN
1993  122551.458333         11.61
1994  149271.541667         21.80
1995  170430.572917         14.17
1996  181751.458333          6.64
1997  200465.062500         10.30
1998  221304.645833         10.40
1999  235870.083333          6.58
2000  265929.906250         12.74
2001  168183.369792        -36.76
2002  196960.166667         17.11
2003  216844.635417         10.10
2004  239390.937500         10.40
2005  246737.390625          3.07
2006  250814.760417          1.65
2007  276288.328125         10.16
2008  280273.541667          1.44
2009  249596.041667        -10.95
2010  295720.744792         18.48
2011  337186.536458         14.02
2012  355128.692708          5.32
2013  368460.385417          3.75
2014  389235.067708          5.64
2015  405598.427083          4.20
2016  405339.401042         -0.06
2017  426947.401042          5.33
2018  451303.666667          5.70
2019  458166.671875          1.52
2020  454666.562500         -0.76
2021  473044.369792          4.04
2022  459962.385417         -2.77
2023  482364.750000          4.87
2024  508375.416667          5.39
2025  511203.531250          0.56

In [34]:
df_filtered = df[~df['연월'].str.startswith('2025')]
result4 = df_filtered.groupby('월')['물동량'].mean()
result4
#2월에만 소폭 감소한 점을 보았을 때 
#일단 바로 예측할 수 있는 것은 2월에는 다른 월보다 날짜일수(28일)가 적기 때문이 아닌가 예상이 됩니다.

월
1     310909.122807
2     289705.484649
3     336095.905702
4     330879.260965
5     334775.949561
6     324812.410088
7     332340.412281
8     321858.833333
9     315166.166667
10    330152.096491
11    326818.006579
12    330815.041667
Name: 물동량, dtype: float64

In [ ]:
df_filtered = df[~df['연월'].str.startswith('2025')]
total1 = df_filtered.groupby('연도')['물동량'].sum()
df_trans1 = df_filtered[
    df_filtered['수출입구분설명'].isin(['수출환적', '수입환적'])
]
trans1 = df_trans1.groupby('연도')['물동량'].sum()
ratio1 = (trans1 / total1) * 100
ratio1
#년도별로 비교했을 때 매년 갈수록 환적 비중이 높아지는 것을 확인할 수 있습니다.
#고로 부산항은 환적 기능을 수행하고 있다고 볼 수 있습니다.

연도
1992          NaN
1993          NaN
1994          NaN
1995          NaN
1996          NaN
1997          NaN
1998          NaN
1999          NaN
2000          NaN
2001    36.457079
2002    41.124898
2003    40.845433
2004    41.701662
2005    43.735129
2006    43.261469
2007    43.821906
2008    43.173507
2009    44.844430
2010    44.218876
2011    45.428871
2012    47.796909
2013    49.465138
2014    50.469474
2015    51.905394
2016    50.553448
2017    50.154534
2018    52.760618
2019    52.918768
2020    55.077567
2021    54.050041
2022    53.291544
2023    53.593446
2024    55.311749
Name: 물동량, dtype: float64

In [67]:
df_filtered = df[~df['연월'].str.startswith('2025')]
total2 = df_filtered.groupby('연도')['물동량'].sum()
df_trans2 = df_filtered[
    df_filtered['수출입구분설명'].isin(['수출', '수입'])
]
trans2 = df_trans2.groupby('연도')['물동량'].sum()
ratio2 = (trans2 / total2) * 100
ratio2

연도
1992    100.000000
1993    100.000000
1994    100.000000
1995    100.000000
1996    100.000000
1997    100.000000
1998    100.000000
1999    100.000000
2000    100.000000
2001     63.542921
2002     58.875102
2003     59.154567
2004     58.298338
2005     56.264871
2006     56.738531
2007     56.178094
2008     56.826493
2009     55.155570
2010     55.781124
2011     54.571129
2012     52.203091
2013     50.534862
2014     49.530526
2015     48.094606
2016     49.446552
2017     49.845466
2018     47.239382
2019     47.081232
2020     44.922433
2021     45.949959
2022     46.708456
2023     46.406554
2024     44.688251
Name: 물동량, dtype: float64

In [ ]:
grouped1 = df.groupby('월')
result1 = grouped1['물동량'].mean()
result1

월
1     318387.497881
2     296525.158898
3     336095.905702
4     330879.260965
5     334775.949561
6     324812.410088
7     332340.412281
8     321858.833333
9     315166.166667
10    330152.096491
11    326818.006579
12    330815.041667
Name: 물동량, dtype: float64

In [29]:
grouped2 = df.groupby('연월')
result2 = grouped2['물동량'].mean()
result2

연월
1992-01     98286.0000
1992-02     97786.0000
1992-03    121179.0000
1992-04    114807.0000
1992-05    111179.5000
              ...
2024-10    512347.6875
2024-11    499525.1875
2024-12    516855.0625
2025-01    531521.1875
2025-02    490885.8750
Name: 물동량, Length: 398, dtype: float64

In [33]:
result3 = df[~df['연월'].str.startswith('2025')].groupby('연월')['물동량'].mean()
print(result3)

연월
1992-01     98286.0000
1992-02     97786.0000
1992-03    121179.0000
1992-04    114807.0000
1992-05    111179.5000
              ...
2024-08    513201.5000
2024-09    469288.0000
2024-10    512347.6875
2024-11    499525.1875
2024-12    516855.0625
Name: 물동량, Length: 396, dtype: float64

In [43]:
df_filtered = df[~df['연월'].str.startswith('2025')]
df_filtered2 = df[df['수출입구분설명'].isin(['수출환적', '수입환적'])]
result5 = df_filtered2.groupby('월')['물동량'].mean()
result5

월
1     348757.370000
2     320292.985000
3     346100.619792
4     350406.406250
5     356506.411458
6     347788.296875
7     355290.947917
8     349679.166667
9     333156.088542
10    352209.687500
11    347663.026042
12    347972.354167
Name: 물동량, dtype: float64

In [51]:
df_filtered = df[~df['연월'].str.startswith('2025')]
df_filtered3 = df_filtered[df_filtered['수출입구분설명'].isin(['수출환적', '수입환적'])]
result7 = df_filtered3.groupby('월')['물동량'].sum()
result7

월
1     16214219.75
2     14881453.75
3     16612829.75
4     16819507.50
5     17112307.75
6     16693838.25
7     17053965.50
8     16784600.00
9     15991492.25
10    16906065.00
11    16687825.25
12    16702673.00
Name: 물동량, dtype: float64

In [ ]:
df_filtered = df[~df['연월'].str.startswith('2025')]
total = df_filtered.groupby('월')['물동량'].sum()
trans = (
    df_filtered[df_filtered['수출입구분설명'].eq('수입환적', '수출환적')]
    .groupby('월')['물동량']
    .sum())
ratio = trans / total * 100
ratio

월
1     8255917.00
2     7314140.75
3     8419061.75
4     8457842.00
5     8590297.00
6     8375244.25
7     8583223.25
8     8461540.25
9     8087570.00
10    8558600.50
11    8301020.75
12    8523570.75
Name: 물동량, dtype: float64

In [54]:
df_filtered = df[~df['연월'].str.startswith('2025')]
df_trans = df_filtered[
    df_filtered['수출입구분설명'].isin(['수출환적', '수입환적'])]

result8 = df_trans.groupby('월')['물동량'].mean()
result8

월
1     337796.244792
2     310030.286458
3     346100.619792
4     350406.406250
5     356506.411458
6     347788.296875
7     355290.947917
8     349679.166667
9     333156.088542
10    352209.687500
11    347663.026042
12    347972.354167
Name: 물동량, dtype: float64

In [ ]:
comparison = pd.DataFrame({
    '전체 월별 평균': result4,
    '환적 월별 평균': result7
})
comparison

         전체 월별 평균     환적 월별 평균
월
1   310909.122807  16214219.75
2   289705.484649  14881453.75
3   336095.905702  16612829.75
4   330879.260965  16819507.50
5   334775.949561  17112307.75
6   324812.410088  16693838.25
7   332340.412281  17053965.50
8   321858.833333  16784600.00
9   315166.166667  15991492.25
10  330152.096491  16906065.00
11  326818.006579  16687825.25
12  330815.041667  16702673.00